### ISSUE TITLE
Legacy mode: Internal client error

### ISSUE THREAD

**Issue by HinchyMinecraft** [Thulinma/MixedModeAuth#2]
Installed the PHP script properly. forwarded session.minecraft.net to my server IP.
If I go to session.minecraft.net/checkserver.jsp, I even get the "The script is installed properly! Yay!" message.
start up game in offline mode: Get this error:

Connection Lost
Internal client error: java.io.FileNotFoundException: http://session.minecraft.net/game/joinserver.jsp?user=Player&sessionId=&serverId=hexdigitstoolazytocopy.

Obviously this is because joinserver.jsp doesn't exist on the server. But there's no joinserver.php script, and forwarding that to checkserver.jsp gives me a different error entirely (Connection Lost / Failed to login: YES).

I also forwarded to plain minecraft.net and www.minecraft.net to see if there were errors in your documentation (the checkserver.php file actually does say to use the hosts file to go to www and not session -- which one's correct?) but they all give Bad Login errors.

...what's the problem? I'd really like to have this working for when minecraft.net goes down during the middle of updating server plugins (seemingly every time there's a Bukkit update; I have crap luck).

(ALSO: running on Nginx. I'll contribute server config once this is sorted out!)

**Comment by Thulinma** [comment]
www is correct for 1.7.\* and lower, session is correct for 1.8.

The problem here is that it looks like you are running the client as well on the machine with the forwarded session hostname. Not really, an issue, but the client also tries to reach the session server. For joinserver.jsp, it expects a reply containing only "ok" in lowercase, just like that. So creating a joinserver.jsp file with just those two letters in it, should fix your problem connecting to the server.

I never included this information in any of the documentation because I assumed nobody would be running client and server on the same machine - looks like I assumed wrong :-)

EDIT: Or, alternatively, use the server mod / client mod combo - it's a little more robust against modifications by mojang and doesn't require changing of hosts files to work.

**Comment by HinchyMinecraft** [comment]
I'm not running client and server on the same computer. My problem was that I thought that the hosts file had to be edited on the client side only!

EDIT: I'd use the server mod if it wasn't for the fact that it's still using CraftBukkit 1240 (you're 2 RBs behind).

**Comment by Thulinma** [comment]
I updated that to RB 1337 earlier today :-)

And yeah, the hosts file only needs to be edited on the server side. It would be a little weird to ask all your players to do something like that, after all ;-)

**Comment by Thulinma** [comment]
Assuming this is no longer an issue nowadays. Re-open if it is :-)
