### ISSUE TITLE
Offline vs Online

### ISSUE THREAD

**Issue by DanielFallon** [Thulinma/MixedModeAuth#26]
Is it possible for the server to selectively behave like an online or offline server depending on whether or not the client is in offline or online mode?

requiring players to have a modded client can be a steep climb.

I don't know enough about the login handshake to figure out how to implement this, but I just thought I'd introduce the possibility

**Comment by Thulinma** [comment]
I wanted to make this plugin do exactly that from the start, but it's impossible because of a technicality in the vanilla minecraft server handshake.
If you want the details I can give them - but suffice to say it's impossible to behave like both online and offline at the same time without a modded client.
